# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            .Net programmr
tagline:          'All things .Net'
description:      'A blog about things .Net (and maybe a bit more) from a .Net developer.'
url:              http://dotnetprogrammr.github.io
baseurl:          /

author:
  name:           'Michael Marshall'
  url:            https://twitter.com/dotnetprogrammr

paginate:         5

# Gems
gems: [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dotnetprogrammr
